"use client";

import Link from "next/link";
import { ArrowRight, CalendarDays, Clock3, Pencil, Trash2 } from "lucide-react";
import { formatAssignmentStatus, formatDueDate, formatPriority, getDueDateTone } from "@/lib/studyflow-format";
import type { Assignment, Course } from "@/types/studyflow";

export function AssignmentCard({ assignment, course, onEdit, onDelete }: { assignment: Assignment; course?: Course; onEdit: () => void; onDelete: (button: HTMLButtonElement) => void }) {
  const dueTone = getDueDateTone(assignment.dueDate, assignment.status);
  return <article className="flex min-w-0 flex-col rounded-[var(--radius-card)] border border-[var(--line)] bg-white p-5 shadow-[0_8px_24px_rgba(16,24,40,0.04)]"><div className="flex min-w-0 items-start justify-between gap-4"><div className="min-w-0"><p className="truncate text-xs font-bold uppercase tracking-[0.14em] text-blue-600">{course?.name ?? "Course unavailable"}</p><h3 className="mt-2 break-words text-lg font-semibold tracking-tight text-slate-950">{assignment.title}</h3></div><span className={`shrink-0 rounded-full px-2.5 py-1 text-xs font-semibold ${assignment.priority === "high" ? "bg-red-50 text-red-800" : assignment.priority === "low" ? "bg-slate-100 text-slate-700" : "bg-amber-50 text-amber-800"}`}>{formatPriority(assignment.priority)}</span></div><div className={`mt-4 flex flex-wrap gap-x-4 gap-y-2 text-sm ${dueTone === "overdue" ? "text-red-700" : "text-[var(--muted)]"}`}><span className={`inline-flex items-center gap-1.5 ${dueTone === "overdue" ? "font-semibold text-red-700" : dueTone === "today" ? "font-semibold text-amber-700" : ""}`}><CalendarDays size={15} aria-hidden="true" />{dueTone === "overdue" ? "Overdue · " : dueTone === "today" ? "Due today · " : ""}{formatDueDate(assignment.dueDate)}</span>{assignment.estimatedMinutes && <span className="inline-flex items-center gap-1.5"><Clock3 size={15} aria-hidden="true" />{assignment.estimatedMinutes} min</span>}</div><div className="mt-4"><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${assignment.status === "completed" ? "bg-emerald-50 text-emerald-800" : assignment.status === "in-progress" ? "bg-blue-50 text-blue-800" : "bg-slate-100 text-slate-700"}`}>{formatAssignmentStatus(assignment.status)}</span></div><div className="mt-5 flex flex-wrap items-center justify-between gap-2 border-t border-[var(--line)] pt-4"><Link href={`/assignments/${assignment.id}`} className="inline-flex items-center gap-1.5 text-sm font-semibold text-blue-700 hover:text-blue-900 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600">Open assignment <ArrowRight size={15} aria-hidden="true" /></Link><div className="flex gap-1"><button type="button" onClick={onEdit} aria-label={`Edit ${assignment.title}`} className="inline-flex h-9 w-9 items-center justify-center rounded-md text-slate-500 transition-colors hover:bg-blue-50 hover:text-blue-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600"><Pencil size={16} aria-hidden="true" /></button><button type="button" onClick={(event) => onDelete(event.currentTarget)} aria-label={`Delete ${assignment.title}`} className="inline-flex h-9 w-9 items-center justify-center rounded-md text-slate-500 transition-colors hover:bg-red-50 hover:text-red-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-700"><Trash2 size={16} aria-hidden="true" /></button></div></div></article>;
}
