"use client";

import { CalendarDays, Pencil, Trash2 } from "lucide-react";
import { formatDueDate, formatPriority } from "@/lib/studyflow-format";
import { getTaskDueState } from "@/lib/studyflow-selectors";
import type { Assignment, Course, Task } from "@/types/studyflow";

export function TaskCard({ task, course, assignment, compact = false, onToggle, onEdit, onDelete }: { task: Task; course?: Course; assignment?: Assignment; compact?: boolean; onToggle: () => void; onEdit?: () => void; onDelete?: (button: HTMLButtonElement) => void }) {
  const dueState = getTaskDueState(task);
  return <article className={`flex min-w-0 items-start gap-3 rounded-[var(--radius-card)] border border-[var(--line)] bg-white ${compact ? "p-4" : "p-5"} shadow-[0_8px_24px_rgba(16,24,40,0.04)]`}><label className="mt-0.5 shrink-0"><span className="sr-only">Mark {task.title} {task.completed ? "incomplete" : "complete"}</span><input type="checkbox" checked={task.completed} onChange={onToggle} className="h-5 w-5 cursor-pointer rounded border-slate-300 accent-blue-600 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600" /></label><div className="min-w-0 flex-1"><div className="flex min-w-0 flex-wrap items-start justify-between gap-2"><h3 className={`break-words text-sm font-semibold ${task.completed ? "text-slate-400 line-through" : "text-slate-900"}`}>{task.title}</h3><span className={`shrink-0 rounded-full px-2 py-1 text-[11px] font-semibold ${task.priority === "high" ? "bg-red-50 text-red-800" : task.priority === "low" ? "bg-slate-100 text-slate-700" : "bg-amber-50 text-amber-800"}`}>{formatPriority(task.priority)}</span></div><div className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-xs text-[var(--muted)]">{course && <span>{course.name}</span>}{assignment && <span>{assignment.title}</span>}{task.dueDate && <span className={`inline-flex items-center gap-1 ${dueState === "overdue" ? "font-semibold text-red-700" : dueState === "today" ? "font-semibold text-amber-700" : ""}`}><CalendarDays size={13} aria-hidden="true" />{dueState === "overdue" ? "Overdue · " : dueState === "today" ? "Due today · " : ""}{formatDueDate(task.dueDate)}</span>}</div>{task.description && !compact && <p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[var(--muted)]">{task.description}</p>}</div>{(onEdit || onDelete) && <div className="flex shrink-0 gap-1"><button type="button" onClick={onEdit} aria-label={`Edit ${task.title}`} className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-500 transition-colors hover:bg-blue-50 hover:text-blue-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600"><Pencil size={15} aria-hidden="true" /></button><button type="button" onClick={(event) => onDelete?.(event.currentTarget)} aria-label={`Delete ${task.title}`} className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-500 transition-colors hover:bg-red-50 hover:text-red-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-700"><Trash2 size={15} aria-hidden="true" /></button></div>}</article>;
}
