"use client";

import { CalendarDays, Pencil, Trash2 } from "lucide-react";
import { formatDueDate, formatPriority } from "@/lib/studyflow-format";
import { getTaskDueState } from "@/lib/studyflow-selectors";
import type { Assignment, Course, Task } from "@/types/studyflow";

export function TaskCard({ task, course, assignment, compact = false, onToggle, onEdit, onDelete }: { task: Task; course?: Course; assignment?: Assignment; compact?: boolean; onToggle: () => void; onEdit?: () => void; onDelete?: (button: HTMLButtonElement) => void }) {
  const dueState = getTaskDueState(task);
  return <article className={`flex min-w-0 items-start gap-3 rounded-[var(--radius-card)] border border-[var(--line)] bg-slate-950/40 ${compact ? "p-4" : "p-5"} shadow-[0_12px_28px_rgba(2,6,23,0.35)]`}><label className="mt-0.5 shrink-0"><span className="sr-only">Mark {task.title} {task.completed ? "incomplete" : "complete"}</span><input type="checkbox" checked={task.completed} onChange={onToggle} className="h-5 w-5 cursor-pointer rounded border-slate-500 accent-cyan-400 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-300" /></label><div className="min-w-0 flex-1"><div className="flex min-w-0 flex-wrap items-start justify-between gap-2"><h3 className={`break-words text-sm font-semibold ${task.completed ? "text-slate-400 line-through" : "text-white"}`}>{task.title}</h3><span className={`shrink-0 rounded-full px-2 py-1 text-[11px] font-semibold ${task.priority === "high" ? "bg-red-500/10 text-red-200 ring-1 ring-red-400/20" : task.priority === "low" ? "bg-slate-500/10 text-slate-200 ring-1 ring-slate-400/20" : "bg-amber-500/10 text-amber-200 ring-1 ring-amber-400/20"}`}>{formatPriority(task.priority)}</span></div><div className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-xs text-slate-300">{course && <span>{course.name}</span>}{assignment && <span>{assignment.title}</span>}{task.dueDate && <span className={`inline-flex items-center gap-1 ${dueState === "overdue" ? "font-semibold text-red-300" : dueState === "today" ? "font-semibold text-amber-200" : "text-slate-300"}`}><CalendarDays size={13} aria-hidden="true" />{dueState === "overdue" ? "Overdue · " : dueState === "today" ? "Due today · " : ""}{formatDueDate(task.dueDate)}</span>}</div>{task.description && !compact && <p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-300">{task.description}</p>}</div>{(onEdit || onDelete) && <div className="flex shrink-0 gap-1"><button type="button" onClick={onEdit} aria-label={`Edit ${task.title}`} className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-300 transition-colors hover:bg-cyan-500/10 hover:text-cyan-200 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-300"><Pencil size={15} aria-hidden="true" /></button><button type="button" onClick={(event) => onDelete?.(event.currentTarget)} aria-label={`Delete ${task.title}`} className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-300 transition-colors hover:bg-red-500/10 hover:text-red-200 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-400"><Trash2 size={15} aria-hidden="true" /></button></div>}</article>;
}
