"use client";

import { formatDueDate } from "@/lib/studyflow-format";
import { getCalendarItemDueState, type CalendarItem } from "@/lib/studyflow-selectors";
import { formatCalendarDate, getWeekdayLabels, isSameLocalDate } from "@/lib/calendar";

export function CalendarMonth({ dates, month, selectedDate, today, weekStartsOn, itemsForDate, onSelectDate }: { dates: Date[]; month: Date; selectedDate: Date; today: Date; weekStartsOn: 0 | 1; itemsForDate: (date: Date) => CalendarItem[]; onSelectDate: (date: Date) => void }) {
  const weekdays = getWeekdayLabels(weekStartsOn);
  return <div className="overflow-hidden rounded-[var(--radius-card)] border border-[var(--line)] bg-white"><div className="grid grid-cols-7 border-b border-[var(--line)] bg-slate-50">{weekdays.map((weekday) => <div key={weekday} className="px-1 py-3 text-center text-[10px] font-bold uppercase tracking-wide text-slate-500 sm:px-2 sm:text-xs">{weekday}</div>)}</div><div className="grid grid-cols-7">{dates.map((date) => { const items = itemsForDate(date); const inMonth = date.getMonth() === month.getMonth(); const isToday = isSameLocalDate(date, today); const isSelected = isSameLocalDate(date, selectedDate); return <button key={date.toISOString()} type="button" onClick={() => onSelectDate(date)} aria-label={`${formatCalendarDate(date)}${isToday ? ", Today" : ""}${items.length ? `, ${items.length} due ${items.length === 1 ? "item" : "items"}` : ", nothing due"}`} aria-current={isToday ? "date" : undefined} aria-pressed={isSelected} className={`group min-w-0 min-h-28 border-b border-r border-[var(--line)] p-1.5 text-left align-top transition-colors last:border-r-0 hover:bg-blue-50 focus-visible:z-10 focus-visible:outline-2 focus-visible:outline-inset focus-visible:outline-blue-600 sm:min-h-32 sm:p-2 ${inMonth ? "" : "bg-slate-50/60 text-slate-400"} ${isSelected ? "bg-blue-50 ring-2 ring-inset ring-blue-500" : ""}`}><span className={`inline-flex h-7 min-w-7 items-center justify-center rounded-full px-1.5 text-xs font-semibold ${isToday ? "bg-blue-600 text-white" : inMonth ? "text-slate-700" : "text-slate-400"}`}>{date.getDate()}</span>{isToday && <span className="sr-only">Today</span>}<div className="mt-1.5 space-y-1">{items.slice(0, 2).map((item) => <CalendarCellItem key={`${item.type}-${item.id}`} item={item} />)}{items.length > 2 && <span className="block truncate px-1 text-[10px] font-semibold text-slate-500">+{items.length - 2} more</span>}</div></button>; })}</div></div>;
}

function CalendarCellItem({ item }: { item: CalendarItem }) {
  const state = getCalendarItemDueState(item);
  return <span title={`${item.type === "assignment" ? "Assignment" : "Task"}: ${item.title} · ${formatDueDate(item.dueDate)}`} className={`block truncate rounded px-1 py-1 text-[10px] font-semibold leading-4 ${item.completed ? "bg-emerald-50 text-emerald-800 line-through" : state === "overdue" ? "bg-red-50 text-red-800" : item.type === "assignment" ? "bg-blue-50 text-blue-800" : "bg-amber-50 text-amber-900"}`}><span aria-hidden="true">{item.type === "assignment" ? "A" : "T"} · </span>{item.title}</span>;
}
