"use client";

import { FileText, Pencil, Trash2 } from "lucide-react";
import { formatDueDate } from "@/lib/studyflow-format";
import type { Course, Note } from "@/types/studyflow";

export function NoteCard({ note, course, onEdit, onDelete }: { note: Note; course?: Course; onEdit: () => void; onDelete: (button: HTMLButtonElement) => void }) {
  const preview = note.content.replace(/\s+/g, " ").trim();
  return <article className="flex min-w-0 flex-col rounded-[var(--radius-card)] border border-[var(--line)] bg-slate-950/40 p-5 shadow-[0_12px_28px_rgba(2,6,23,0.35)]"><div className="flex min-w-0 items-start justify-between gap-3"><div className="flex min-w-0 items-start gap-3"><span className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-md bg-cyan-500/10 text-cyan-300"><FileText size={16} aria-hidden="true" /></span><div className="min-w-0"><h2 className="break-words text-base font-semibold tracking-tight text-white">{note.title}</h2><p className="mt-1 truncate text-xs text-slate-300">{course?.name ?? "Personal note"}</p></div></div><div className="flex shrink-0 gap-1"><button type="button" onClick={onEdit} aria-label={`Edit ${note.title}`} className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-300 transition-colors hover:bg-cyan-500/10 hover:text-cyan-200 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-300"><Pencil size={15} aria-hidden="true" /></button><button type="button" onClick={(event) => onDelete(event.currentTarget)} aria-label={`Delete ${note.title}`} className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-300 transition-colors hover:bg-red-500/10 hover:text-red-200 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-400"><Trash2 size={15} aria-hidden="true" /></button></div></div><p className="mt-5 line-clamp-4 whitespace-pre-wrap break-words text-sm leading-6 text-slate-300">{preview}</p><p className="mt-5 border-t border-[var(--line)] pt-3 text-xs text-slate-400">Updated {formatDueDate(note.updatedAt)}</p></article>;
}
