"use client";

import Link from "next/link";
import { ArrowRight, BookOpen, Pencil, Trash2, UserRound } from "lucide-react";
import type { Course } from "@/types/studyflow";

export function CourseCard({ course, assignmentCount, upcomingCount, progress, onEdit, onDelete }: { course: Course; assignmentCount: number; upcomingCount: number; progress: number; onEdit: () => void; onDelete: (button: HTMLButtonElement) => void }) {
  return <article className="flex min-w-0 flex-col rounded-[var(--radius-card)] border border-[var(--line)] border-l-4 bg-white p-5 shadow-[0_8px_24px_rgba(16,24,40,0.04)]" style={{ borderLeftColor: course.color ?? "var(--brand)" }}>
    <div className="flex min-w-0 items-start justify-between gap-4"><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[var(--muted)]">{course.code || "Course"}</p><h2 className="mt-2 break-words text-lg font-semibold tracking-tight text-slate-950">{course.name}</h2></div><span className="mt-1 h-3 w-3 shrink-0 rounded-full" style={{ backgroundColor: course.color ?? "var(--brand)" }} aria-label={`${course.name} color`} /> </div>
    <div className="mt-4 min-h-10 space-y-1 text-sm text-[var(--muted)]">{course.instructor && <p className="flex items-center gap-2"><UserRound size={14} aria-hidden="true" />{course.instructor}</p>}{course.semester && <p>{course.semester}</p>}</div>
    <div className="mt-5"><div className="flex items-baseline justify-between text-xs"><span className="font-semibold text-slate-700">Progress</span><span className="text-[var(--muted)]">{progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600 transition-[width] duration-300" style={{ width: `${progress}%` }} /></div></div>
    <dl className="mt-5 grid grid-cols-2 gap-3 border-t border-[var(--line)] pt-4"><div><dt className="text-xs text-[var(--muted)]">Assignments</dt><dd className="mt-1 flex items-center gap-1.5 text-sm font-semibold text-slate-800"><BookOpen size={14} className="text-blue-600" aria-hidden="true" />{assignmentCount}</dd></div><div><dt className="text-xs text-[var(--muted)]">Upcoming</dt><dd className="mt-1 text-sm font-semibold text-slate-800">{upcomingCount}</dd></div></dl>
    <div className="mt-5 flex flex-wrap items-center justify-between gap-2"><Link href={`/courses/${course.id}`} className="inline-flex items-center gap-1.5 text-sm font-semibold text-blue-700 hover:text-blue-900 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600">Open course <ArrowRight size={15} aria-hidden="true" /></Link><div className="flex gap-1"><button type="button" onClick={onEdit} aria-label={`Edit ${course.name}`} className="inline-flex h-9 w-9 items-center justify-center rounded-md text-slate-500 transition-colors hover:bg-blue-50 hover:text-blue-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600"><Pencil size={16} aria-hidden="true" /></button><button type="button" onClick={(event) => onDelete(event.currentTarget)} aria-label={`Delete ${course.name}`} className="inline-flex h-9 w-9 items-center justify-center rounded-md text-slate-500 transition-colors hover:bg-red-50 hover:text-red-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-700"><Trash2 size={16} aria-hidden="true" /></button></div></div>
  </article>;
}
