"use client";

import Link from "next/link";
import { ArrowRight, BookOpen, CheckCircle2, GraduationCap, ListTodo } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { formatDueDate, formatPriority } from "@/lib/studyflow-format";
import { TaskCard } from "@/components/tasks/task-card";
import { useStudyFlow } from "@/providers/studyflow-provider";

export function DashboardWorkspace() {
  const { data, isHydrated, getPendingTasks, getUpcomingAssignments, getOrderedTasks, getCourseById, getAssignmentById, toggleTask, getCourseProgress, getTaskCompletionPercentage } = useStudyFlow();

  if (!isHydrated) return <DashboardSkeleton />;

  const pendingTasks = getPendingTasks();
  const upcomingAssignments = getUpcomingAssignments();
  const orderedPendingTasks = getOrderedTasks().filter((task) => !task.completed).slice(0, 4);
  const completedTasks = data.tasks.filter((task) => task.completed).length;
  const hasProductData = data.courses.length > 0 || data.assignments.length > 0 || data.tasks.length > 0;

  if (!hasProductData) return <FirstRunDashboard />;

  return <>
    <header className="border-b border-[var(--line)] pb-8"><p className="mb-3 text-xs font-bold uppercase tracking-[0.16em] text-blue-600">Today</p><h1 className="text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl">{getGreeting()}</h1><p className="mt-3 text-base leading-7 text-[var(--muted)]">Here&apos;s an honest view of the work in your StudyFlow workspace.</p></header>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Study overview"><Metric label="Courses" value={String(data.courses.length)} note={data.courses.length === 1 ? "Active course" : "Active courses"} icon={GraduationCap} /><Metric label="Pending tasks" value={String(pendingTasks.length)} note={pendingTasks.length ? "Ready for attention" : "All tasks complete"} icon={ListTodo} /><Metric label="Upcoming assignments" value={String(upcomingAssignments.length)} note={upcomingAssignments[0] ? `Next: ${formatDueDate(upcomingAssignments[0].dueDate)}` : "No open deadlines"} icon={BookOpen} /><Metric label="Task completion" value={`${getTaskCompletionPercentage()}%`} note={`${completedTasks} completed`} icon={CheckCircle2} /></section>
    <section className="mt-8 grid gap-5 lg:grid-cols-[1.25fr_1fr]"><DashboardPanel title="Priority tasks" actionLabel="View tasks" actionHref="/tasks"><div className="divide-y divide-[var(--line)]">{orderedPendingTasks.length ? orderedPendingTasks.map((task) => <div key={task.id} className="py-3 first:pt-0 last:pb-0"><TaskCard task={task} compact course={task.courseId ? getCourseById(task.courseId) : undefined} assignment={task.assignmentId ? getAssignmentById(task.assignmentId) : undefined} onToggle={() => toggleTask(task.id)} /></div>) : <EmptyPanelCopy text="No open tasks need attention right now." href="/tasks" linkText="Open tasks" />}</div></DashboardPanel><DashboardPanel title="Upcoming assignments" actionLabel="View all" actionHref="/assignments"><div className="divide-y divide-[var(--line)]">{upcomingAssignments.slice(0, 4).length ? upcomingAssignments.slice(0, 4).map((assignment) => <Link key={assignment.id} href={`/assignments/${assignment.id}`} className="flex items-center justify-between gap-4 py-3 first:pt-0 last:pb-0 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600"><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-800">{assignment.title}</p><p className="mt-1 truncate text-xs text-[var(--muted)]">{getCourseById(assignment.courseId)?.name ?? "Course unavailable"} · {formatPriority(assignment.priority)} priority</p></div><span className="shrink-0 text-right text-xs font-medium text-slate-500">{formatDueDate(assignment.dueDate)}</span></Link>) : <EmptyPanelCopy text="No upcoming assignments yet." href="/assignments" linkText="Open assignments" />}</div></DashboardPanel></section>
    <section className="mt-5 rounded-[var(--radius-card)] border border-[var(--line)] bg-white p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-semibold text-slate-950">Course progress</h2><p className="mt-1 text-sm text-[var(--muted)]">Progress is based on completed assignments and tasks.</p></div><Link href="/courses" className="inline-flex items-center gap-1.5 text-sm font-semibold text-blue-700 hover:text-blue-900 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600">View courses <ArrowRight size={15} aria-hidden="true" /></Link></div>{data.courses.length ? <div className="mt-6 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{data.courses.slice(0, 6).map((course) => <Progress key={course.id} label={course.name} value={getCourseProgress(course.id)} />)}</div> : <p className="mt-6 rounded-md bg-slate-50 px-4 py-4 text-sm leading-6 text-[var(--muted)]">Add a course to see progress connected to your coursework.</p>}</section>
  </>;
}

function getGreeting(): string { const hour = new Date().getHours(); return hour < 12 ? "Good morning." : hour < 18 ? "Good afternoon." : "Good evening."; }
function Metric({ label, value, note, icon: Icon }: { label: string; value: string; note: string; icon: LucideIcon }) { return <div className="rounded-[var(--radius-card)] border border-[var(--line)] bg-white p-5 transition-shadow hover:shadow-[0_8px_24px_rgba(16,24,40,0.06)]"><div className="flex items-center justify-between"><p className="text-sm text-[var(--muted)]">{label}</p><Icon size={18} strokeWidth={1.8} className="text-blue-600" aria-hidden="true" /></div><p className="mt-5 text-2xl font-semibold tracking-tight text-slate-950">{value}</p><p className="mt-1 text-xs font-medium text-[var(--muted)]">{note}</p></div>; }
function DashboardPanel({ title, actionLabel, actionHref, children }: { title: string; actionLabel: string; actionHref: string; children: React.ReactNode }) { return <div className="rounded-[var(--radius-card)] border border-[var(--line)] bg-white p-5 sm:p-6"><div className="flex items-center justify-between gap-4"><h2 className="font-semibold text-slate-950">{title}</h2><Link href={actionHref} className="inline-flex items-center gap-1 text-xs font-semibold text-blue-600 hover:text-blue-800 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600">{actionLabel}<ArrowRight size={13} aria-hidden="true" /></Link></div><div className="mt-5">{children}</div></div>; }
function EmptyPanelCopy({ text, href, linkText }: { text: string; href: string; linkText: string }) { return <div className="rounded-md bg-slate-50 px-4 py-5 text-sm leading-6 text-[var(--muted)]"><p>{text}</p><Link href={href} className="mt-2 inline-flex items-center gap-1 font-semibold text-blue-700 hover:text-blue-900 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600">{linkText}<ArrowRight size={14} aria-hidden="true" /></Link></div>; }
function Progress({ label, value }: { label: string; value: number }) { return <div><div className="flex justify-between gap-3 text-sm"><span className="min-w-0 truncate font-medium text-slate-700">{label}</span><span className="shrink-0 text-[var(--muted)]">{value}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600 transition-[width] duration-300" style={{ width: `${value}%` }} /></div></div>; }
function FirstRunDashboard() { return <><header className="border-b border-[var(--line)] pb-8"><p className="mb-3 text-xs font-bold uppercase tracking-[0.16em] text-blue-600">Your workspace</p><h1 className="text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl">Welcome to StudyFlow</h1><p className="mt-3 max-w-2xl text-base leading-7 text-[var(--muted)]">Start with your first course. From there, you can organize assignments and break them into manageable tasks.</p></header><section className="mt-8 rounded-[var(--radius-card)] border border-dashed border-slate-300 bg-white px-6 py-16 text-center sm:px-10"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-blue-50 text-blue-600"><GraduationCap size={23} aria-hidden="true" /></div><h2 className="mt-5 text-xl font-semibold tracking-tight text-slate-950">Build your study workspace</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[var(--muted)]">Once you add a course, your deadlines, tasks, and real progress will appear here.</p><div className="mt-6 flex flex-wrap justify-center gap-3"><Link href="/courses" className="inline-flex h-10 items-center gap-2 rounded-md bg-blue-600 px-4 text-sm font-semibold text-white hover:bg-blue-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600">Add your first course <ArrowRight size={16} aria-hidden="true" /></Link><Link href="/ai" className="inline-flex h-10 items-center rounded-md border border-[var(--line)] bg-white px-4 text-sm font-semibold text-slate-700 hover:bg-slate-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600">Open StudyFlow AI</Link></div></section></>; }
function DashboardSkeleton() { return <div role="status" aria-label="Loading dashboard" className="animate-pulse"><div className="h-4 w-20 rounded bg-slate-200" /><div className="mt-4 h-10 w-72 max-w-full rounded bg-slate-200" /><div className="mt-3 h-5 w-96 max-w-full rounded bg-slate-200" /><div className="mt-10 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="h-32 rounded-[var(--radius-card)] bg-slate-200" /><div className="h-32 rounded-[var(--radius-card)] bg-slate-200" /><div className="h-32 rounded-[var(--radius-card)] bg-slate-200" /><div className="h-32 rounded-[var(--radius-card)] bg-slate-200" /></div><div className="mt-8 grid gap-5 lg:grid-cols-2"><div className="h-64 rounded-[var(--radius-card)] bg-slate-200" /><div className="h-64 rounded-[var(--radius-card)] bg-slate-200" /></div></div>; }
